name: Terraform Infrastructure CI/CD

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-infra.yml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-infra.yml'

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform -chdir=terraform/environments/dev init

      - name: Terraform Format
        run: terraform -chdir=terraform/environments/dev fmt -check

      - name: Terraform Validate
        run: terraform -chdir=terraform/environments/dev validate

      - name: Terraform Plan
        run: terraform -chdir=terraform/environments/dev plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      # Uncomment to enable auto-apply (use with caution)
      # - name: Terraform Apply
      #   run: terraform -chdir=terraform/environments/dev apply -auto-approve
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: us-east-1
